source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'

# Ruby hệ thống của macOS là 2.6.10. Bundler mặc định chọn ffi mới nhất, bản đó
# đòi Ruby >= 3.0 và cả quá trình resolve hỏng ngay ở đó. 1.15.5 là bản cuối còn
# chạy với 2.6. Xoá dòng này khi máy build đã có Ruby >= 3.0 (rbenv/Homebrew).
gem 'ffi', '1.15.5'
